In [1]:
!pip install pennylane

import pennylane as qml
from pennylane import numpy as np

Requirement already satisfied: pennylane in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (0.31.1)
Requirement already satisfied: toml in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from pennylane) (0.10.2)
Requirement already satisfied: rustworkx in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from pennylane) (0.13.1)
Requirement already satisfied: autoray<=0.6.3,>=0.3.1 in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from pennylane) (0.6.3)
Requirement already satisfied: autograd<=1.5 in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from pennylane) (1.5)
Requirement already satisfied: requests in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from pennylane) (2.28.1)
Requirement already satisfied: appdirs in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from pennylane) (1.4.4)
Requirement already satisfied: networkx in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from pennylane) (2.8.4)
Requirement already satisfied: semantic-version>=2.7 in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from pennylane) (2.10.0)
Requirement already satisfied: pennylane-lightning>=0.31 in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from pennylane) (0.31.0)
Requirement already satisfied: typing-extensions in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from pennylane) (4.7.1)
Requirement already satisfied: numpy<1.24 in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from pennylane) (1.23.5)
Requirement already satisfied: scipy in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from pennylane) (1.10.0)
Requirement already satisfied: cachetools in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from pennylane) (5.3.1)
Requirement already satisfied: future>=0.15.2 in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from autograd<=1.5->pennylane) (0.18.3)
Requirement already satisfied: charset-normalizer<3,>=2 in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from requests->pennylane) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from requests->pennylane) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from requests->pennylane) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/jonathanmontes/anaconda3/lib/python3.10/site-packages (from requests->pennylane) (1.26.14)

In [2]:
# basis encoding
wires = range(3) # Number of qubits.
basis_dev = qml.device("default.qubit",wires)

@qml.qnode(basis_dev)
def basis_encoder(data):
  qml.BasisEmbedding(data,wires)
  return qml.state()

# Examples:

In [3]:
basis_encoder([1,1,1])

tensor([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j], requires_grad=True)

In [28]:
print(basis_encoder([1,1,1]))

[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j]

In [29]:
print(qml.draw(basis_encoder, expansion_strategy="device")([1,1,1]))

0: ──X─┤  State
1: ──X─┤  State
2: ──X─┤  State

In [4]:
basis_encoder(7)

tensor([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j], requires_grad=True)

We can observe that the basis Embbeding can translate the bit 111 to the quantum base stat $\ket{111}$. Or is equivalent to translate the number 7 directly and we get the same base.

# Dataset

In [5]:
import pandas as pd

In [6]:
nombres = ['Estatura' , 'Peso' , 'Pie' , 'Brazo' , 'Espalda' ,'Craneo' , 'RodTobi']

In [7]:
df = pd.read_csv('DatosFisher_1.csv' , names = nombres)

In [8]:
df

    Estatura  Peso   Pie  Brazo  Espalda  Craneo  RodTobi
0        159    49  36.0   68.0     42.0    57.0     40.0
1        164    62  39.0   73.0     44.0    55.0     44.0
2        172    65  38.0   75.0     48.0    58.0     44.0
3        167    52  37.0   73.0     41.5    58.0     44.0
4        164    51  36.0   71.0     44.5    54.0     40.0
5        161    67  38.0   71.0     44.0    56.0     42.0
6        168    48  39.0   72.5     41.0    54.5     43.0
7        181    74  43.0   74.0     50.0    60.0     47.0
8        183    74  41.0   79.0     47.5    59.5     47.0
9        158    50  36.0   68.5     44.0    57.0     41.0
10       156    65  36.0   68.0     46.0    58.0     41.0
11       173    64  40.0   79.0     48.0    56.5     47.0
12       158    43  36.0   68.0     43.0    55.0     39.0
13       178    74  42.0   75.0     50.0    59.0     45.0
14       181    76  43.0   83.0     51.0    57.0     43.0
15       182    91  41.0   83.0     53.0    59.0     43.0
16       176    73  42.0   78.0     48.0    58.0     45.0
17       162    68  39.0   72.0     44.0    59.0     42.0
18       156    52  36.0   67.0     36.0    56.0     41.0
19       152    45  34.0   66.0     40.0    55.0     38.0
20       181    80  43.0   76.0     49.0    57.0     46.0
21       173    69  41.0   74.0     48.0    56.0     44.0
22       155    53  36.0   67.0     43.0    56.0     38.0
23       189    87  45.0   82.0     53.0    61.0     52.0
24       170    70  38.0   73.0     45.0    56.0     43.0
25       170    67  40.0   77.0     46.5    58.0     44.5
26       168    56  37.5   70.5     48.0    60.0     40.0

In [5]:
df.shape

(27, 7)

In [9]:
df1 = df.iloc[:,0:2]

In [10]:
df1

    Estatura  Peso
0        159    49
1        164    62
2        172    65
3        167    52
4        164    51
5        161    67
6        168    48
7        181    74
8        183    74
9        158    50
10       156    65
11       173    64
12       158    43
13       178    74
14       181    76
15       182    91
16       176    73
17       162    68
18       156    52
19       152    45
20       181    80
21       173    69
22       155    53
23       189    87
24       170    70
25       170    67
26       168    56

# Function to determine with this new dataframe with two variables how many qubits are needed

In [11]:
max_value_Estatura = df1['Estatura'].max()
max_value_Peso = df1['Peso'].max()
print(max_value_Estatura)
print(max_value_Peso)
binary_Est = bin(max_value_Estatura)
binary_Peso= bin(max_value_Peso)
print("Binary representation of max value in Estatura:", binary_Est)
print("Binary representation of max value in Peso:", binary_Peso)

189
91
Binary representation of max value in Estatura: 0b10111101
Binary representation of max value in Peso: 0b1011011

In [12]:
# Number of Qubits needed:
a = len(binary_Est[2:])
b = len(binary_Peso[2:])
c = a+b
print("Number of qubits needed:", c)

Number of qubits needed: 15

In [23]:
df2 = df1.iloc[:,0:2]

In [24]:
df2

    Estatura  Peso
0        159    49
1        164    62
2        172    65
3        167    52
4        164    51
5        161    67
6        168    48
7        181    74
8        183    74
9        158    50
10       156    65
11       173    64
12       158    43
13       178    74
14       181    76
15       182    91
16       176    73
17       162    68
18       156    52
19       152    45
20       181    80
21       173    69
22       155    53
23       189    87
24       170    70
25       170    67
26       168    56

# Base Embedding example for two sambles with two features

In [31]:
from pennylane.templates.embeddings import BasisEmbedding

# quantum device where you want to run and how many Qubits
dev = qml.device('default.qubit', wires=6)

@qml.qnode(dev)
def circuit(data):
    for i in range(6):
        qml.Hadamard(i)
    for i in range(len(data)):
        BasisEmbedding(features=data[i], wires=range(6),do_queue=True)
    return  qml.state()

data=[[1,0,1,1,1,0],
      [1,0,0,0,0,1]]

circuit(data)

/Users/jonathanmontes/anaconda3/lib/python3.10/site-packages/pennylane/operation.py:1034: UserWarning: The do_queue keyword argument is deprecated. Instead of setting it to False, use qml.queuing.QueuingManager.stop_recording()
  warnings.warn(do_queue_deprecation_warning, UserWarning)

tensor([0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j,
        0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j,
        0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j,
        0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j,
        0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j,
        0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j,
        0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j,
        0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j,
        0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j,
        0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j,
        0.125+0.j, 0.125+0.j, 0.125+0.j, 0.125+0.j], requires_grad=True)

In [37]:
# Apply operations on the quantum state (e.g., gates, measurements, etc.)
dev1 = qml.device('default.qubit', wires=6)

@qml.qnode(dev1)
def prob(data):
    for i in range(len(data)):
     qml.RY(data[i], wires=i)

    return qml.probs(wires=range(6))

# Evaluate the quantum circuit with the data and parameters
probs = circuit(data)
print("Probabilities:", probs)

Probabilities: [0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j
 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j
 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j
 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j
 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j
 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j
 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j
 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j
 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j 0.125+0.j
 0.125+0.j]

/Users/jonathanmontes/anaconda3/lib/python3.10/site-packages/pennylane/operation.py:1034: UserWarning: The do_queue keyword argument is deprecated. Instead of setting it to False, use qml.queuing.QueuingManager.stop_recording()
  warnings.warn(do_queue_deprecation_warning, UserWarning)

# Embedding the Fisher's data set

In [43]:
df2

    Estatura  Peso
0        159    49
1        164    62
2        172    65
3        167    52
4        164    51
5        161    67
6        168    48
7        181    74
8        183    74
9        158    50
10       156    65
11       173    64
12       158    43
13       178    74
14       181    76
15       182    91
16       176    73
17       162    68
18       156    52
19       152    45
20       181    80
21       173    69
22       155    53
23       189    87
24       170    70
25       170    67
26       168    56

In [46]:
a = []
for i in df2['Estatura']:
    b = bin(i)
    a.append(b)
df2['Est_bin']=a

/var/folders/y0/flp0gyl545bd055znrzsy1vh0000gn/T/ipykernel_1024/3069026730.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Est_bin']=a

In [47]:
df2

    Estatura  Peso     Est_bin
0        159    49  0b10011111
1        164    62  0b10100100
2        172    65  0b10101100
3        167    52  0b10100111
4        164    51  0b10100100
5        161    67  0b10100001
6        168    48  0b10101000
7        181    74  0b10110101
8        183    74  0b10110111
9        158    50  0b10011110
10       156    65  0b10011100
11       173    64  0b10101101
12       158    43  0b10011110
13       178    74  0b10110010
14       181    76  0b10110101
15       182    91  0b10110110
16       176    73  0b10110000
17       162    68  0b10100010
18       156    52  0b10011100
19       152    45  0b10011000
20       181    80  0b10110101
21       173    69  0b10101101
22       155    53  0b10011011
23       189    87  0b10111101
24       170    70  0b10101010
25       170    67  0b10101010
26       168    56  0b10101000

In [48]:
c = []
for i in df2['Est_bin']:
    #slicing 
    d = i[2:]
    c.append(d)
df2['Estatura_bin']=c

/var/folders/y0/flp0gyl545bd055znrzsy1vh0000gn/T/ipykernel_1024/1483000876.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Estatura_bin']=c

In [51]:
df2

    Estatura  Peso     Est_bin Estatura_bin
0        159    49  0b10011111     10011111
1        164    62  0b10100100     10100100
2        172    65  0b10101100     10101100
3        167    52  0b10100111     10100111
4        164    51  0b10100100     10100100
5        161    67  0b10100001     10100001
6        168    48  0b10101000     10101000
7        181    74  0b10110101     10110101
8        183    74  0b10110111     10110111
9        158    50  0b10011110     10011110
10       156    65  0b10011100     10011100
11       173    64  0b10101101     10101101
12       158    43  0b10011110     10011110
13       178    74  0b10110010     10110010
14       181    76  0b10110101     10110101
15       182    91  0b10110110     10110110
16       176    73  0b10110000     10110000
17       162    68  0b10100010     10100010
18       156    52  0b10011100     10011100
19       152    45  0b10011000     10011000
20       181    80  0b10110101     10110101
21       173    69  0b10101101     10101101
22       155    53  0b10011011     10011011
23       189    87  0b10111101     10111101
24       170    70  0b10101010     10101010
25       170    67  0b10101010     10101010
26       168    56  0b10101000     10101000

In [52]:
f = []
for i in df2['Peso']:
    pbin = bin(i)
    f.append(pbin)
df2['Peso_bin']=f

/var/folders/y0/flp0gyl545bd055znrzsy1vh0000gn/T/ipykernel_1024/2788417811.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Peso_bin']=f

In [53]:
n_f = []
for i in df2['Peso_bin']:
    #slicing 
    h = i[2:]
    n_f.append(h)
df2['Peso_binary']=n_f

/var/folders/y0/flp0gyl545bd055znrzsy1vh0000gn/T/ipykernel_1024/3802608448.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Peso_binary']=n_f

In [54]:
df2

    Estatura  Peso     Est_bin Estatura_bin   Peso_bin Peso_binary
0        159    49  0b10011111     10011111   0b110001      110001
1        164    62  0b10100100     10100100   0b111110      111110
2        172    65  0b10101100     10101100  0b1000001     1000001
3        167    52  0b10100111     10100111   0b110100      110100
4        164    51  0b10100100     10100100   0b110011      110011
5        161    67  0b10100001     10100001  0b1000011     1000011
6        168    48  0b10101000     10101000   0b110000      110000
7        181    74  0b10110101     10110101  0b1001010     1001010
8        183    74  0b10110111     10110111  0b1001010     1001010
9        158    50  0b10011110     10011110   0b110010      110010
10       156    65  0b10011100     10011100  0b1000001     1000001
11       173    64  0b10101101     10101101  0b1000000     1000000
12       158    43  0b10011110     10011110   0b101011      101011
13       178    74  0b10110010     10110010  0b1001010     1001010
14       181    76  0b10110101     10110101  0b1001100     1001100
15       182    91  0b10110110     10110110  0b1011011     1011011
16       176    73  0b10110000     10110000  0b1001001     1001001
17       162    68  0b10100010     10100010  0b1000100     1000100
18       156    52  0b10011100     10011100   0b110100      110100
19       152    45  0b10011000     10011000   0b101101      101101
20       181    80  0b10110101     10110101  0b1010000     1010000
21       173    69  0b10101101     10101101  0b1000101     1000101
22       155    53  0b10011011     10011011   0b110101      110101
23       189    87  0b10111101     10111101  0b1010111     1010111
24       170    70  0b10101010     10101010  0b1000110     1000110
25       170    67  0b10101010     10101010  0b1000011     1000011
26       168    56  0b10101000     10101000   0b111000      111000

In [58]:
def join_binary_numbers(row):
    return row['Estatura_bin'] + row['Peso_binary']
df2['Bin_to_qubit']= df2.apply(join_binary_numbers, axis=1)

/var/folders/y0/flp0gyl545bd055znrzsy1vh0000gn/T/ipykernel_1024/3739569078.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Bin_to_qubit']= df2.apply(join_binary_numbers, axis=1)

In [59]:
df2

,Estatura,Peso,Est_bin,Estatura_bin,Peso_bin,Peso_binary,Bin_to_qubit
0,159,49,0b10011111,10011111,0b110001,110001,10011111110001
1,164,62,0b10100100,10100100,0b111110,111110,10100100111110
2,172,65,0b10101100,10101100,0b1000001,1000001,101011001000001
3,167,52,0b10100111,10100111,0b110100,110100,10100111110100
4,164,51,0b10100100,10100100,0b110011,110011,10100100110011
5,161,67,0b10100001,10100001,0b1000011,1000011,101000011000011
6,168,48,0b10101000,10101000,0b110000,110000,10101000110000
7,181,74,0b10110101,10110101,0b1001010,1001010,101101011001010
8,183,74,0b10110111,10110111,0b1001010,1001010,101101111001010
9,158,50,0b10011110,10011110,0b110010,110010,10011110110010
10,156,65,0b10011100,10011100,0b1000001,1000001,100111001000001
11,173,64,0b10101101,10101101,0b1000000,1000000,101011011000000
12,158,43,0b10011110,10011110,0b101011,101011,10011110101011
13,178,74,0b10110010,10110010,0b1001010,1001010,101100101001010
14,181,76,0b10110101,10110101,0b1001100,1001100,101101011001100
15,182,91,0b10110110,10110110,0b1011011,1011011,101101101011011
16,176,73,0b10110000,10110000,0b1001001,1001001,101100001001001
17,162,68,0b10100010,10100010,0b1000100,1000100,101000101000100
18,156,52,0b10011100,10011100,0b110100,110100,10011100110100
19,152,45,0b10011000,10011000,0b101101,101101,10011000101101
20,181,80,0b10110101,10110101,0b1010000,1010000,101101011010000
21,173,69,0b10101101,10101101,0b1000101,1000101,101011011000101
22,155,53,0b10011011,10011011,0b110101,110101,10011011110101
23,189,87,0b10111101,10111101,0b1010111,1010111,101111011010111
24,170,70,0b10101010,10101010,0b1000110,1000110,101010101000110
25,170,67,0b10101010,10101010,0b1000011,1000011,101010101000011
26,168,56,0b10101000,10101000,0b111000,111000,10101000111000

Transformation of the inputs in the column Bin_to_qubit to a list and then to a tensor:

In [78]:
# Function to pad binary strings with leading zeros to make them 15 digits long
def pad_binary(binary_string):
    return binary_string.zfill(15)

# Apply the function to each row
df2['Bin_to_qubit_15'] = df2['Bin_to_qubit'].apply(pad_binary)

print(df2)

    Estatura  Peso     Est_bin Estatura_bin   Peso_bin Peso_binary  \
0        159    49  0b10011111     10011111   0b110001      110001
1        164    62  0b10100100     10100100   0b111110      111110
2        172    65  0b10101100     10101100  0b1000001     1000001
3        167    52  0b10100111     10100111   0b110100      110100
4        164    51  0b10100100     10100100   0b110011      110011
5        161    67  0b10100001     10100001  0b1000011     1000011
6        168    48  0b10101000     10101000   0b110000      110000
7        181    74  0b10110101     10110101  0b1001010     1001010
8        183    74  0b10110111     10110111  0b1001010     1001010
9        158    50  0b10011110     10011110   0b110010      110010
10       156    65  0b10011100     10011100  0b1000001     1000001
11       173    64  0b10101101     10101101  0b1000000     1000000
12       158    43  0b10011110     10011110   0b101011      101011
13       178    74  0b10110010     10110010  0b1001010     1001010
14       181    76  0b10110101     10110101  0b1001100     1001100
15       182    91  0b10110110     10110110  0b1011011     1011011
16       176    73  0b10110000     10110000  0b1001001     1001001
17       162    68  0b10100010     10100010  0b1000100     1000100
18       156    52  0b10011100     10011100   0b110100      110100
19       152    45  0b10011000     10011000   0b101101      101101
20       181    80  0b10110101     10110101  0b1010000     1010000
21       173    69  0b10101101     10101101  0b1000101     1000101
22       155    53  0b10011011     10011011   0b110101      110101
23       189    87  0b10111101     10111101  0b1010111     1010111
24       170    70  0b10101010     10101010  0b1000110     1000110
25       170    67  0b10101010     10101010  0b1000011     1000011
26       168    56  0b10101000     10101000   0b111000      111000

       Bin_to_qubit  Bin_to_qubit_15
0    10011111110001  010011111110001
1    10100100111110  010100100111110
2   101011001000001  101011001000001
3    10100111110100  010100111110100
4    10100100110011  010100100110011
5   101000011000011  101000011000011
6    10101000110000  010101000110000
7   101101011001010  101101011001010
8   101101111001010  101101111001010
9    10011110110010  010011110110010
10  100111001000001  100111001000001
11  101011011000000  101011011000000
12   10011110101011  010011110101011
13  101100101001010  101100101001010
14  101101011001100  101101011001100
15  101101101011011  101101101011011
16  101100001001001  101100001001001
17  101000101000100  101000101000100
18   10011100110100  010011100110100
19   10011000101101  010011000101101
20  101101011010000  101101011010000
21  101011011000101  101011011000101
22   10011011110101  010011011110101
23  101111011010111  101111011010111
24  101010101000110  101010101000110
25  101010101000011  101010101000011
26   10101000111000  010101000111000

/var/folders/y0/flp0gyl545bd055znrzsy1vh0000gn/T/ipykernel_1024/1709040399.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Bin_to_qubit_15'] = df2['Bin_to_qubit'].apply(pad_binary)

In [79]:
df2

,Estatura,Peso,Est_bin,Estatura_bin,Peso_bin,Peso_binary,Bin_to_qubit,Bin_to_qubit_15
0,159,49,0b10011111,10011111,0b110001,110001,10011111110001,010011111110001
1,164,62,0b10100100,10100100,0b111110,111110,10100100111110,010100100111110
2,172,65,0b10101100,10101100,0b1000001,1000001,101011001000001,101011001000001
3,167,52,0b10100111,10100111,0b110100,110100,10100111110100,010100111110100
4,164,51,0b10100100,10100100,0b110011,110011,10100100110011,010100100110011
5,161,67,0b10100001,10100001,0b1000011,1000011,101000011000011,101000011000011
6,168,48,0b10101000,10101000,0b110000,110000,10101000110000,010101000110000
7,181,74,0b10110101,10110101,0b1001010,1001010,101101011001010,101101011001010
8,183,74,0b10110111,10110111,0b1001010,1001010,101101111001010,101101111001010
9,158,50,0b10011110,10011110,0b110010,110010,10011110110010,010011110110010
10,156,65,0b10011100,10011100,0b1000001,1000001,100111001000001,100111001000001
11,173,64,0b10101101,10101101,0b1000000,1000000,101011011000000,101011011000000
12,158,43,0b10011110,10011110,0b101011,101011,10011110101011,010011110101011
13,178,74,0b10110010,10110010,0b1001010,1001010,101100101001010,101100101001010
14,181,76,0b10110101,10110101,0b1001100,1001100,101101011001100,101101011001100
15,182,91,0b10110110,10110110,0b1011011,1011011,101101101011011,101101101011011
16,176,73,0b10110000,10110000,0b1001001,1001001,101100001001001,101100001001001
17,162,68,0b10100010,10100010,0b1000100,1000100,101000101000100,101000101000100
18,156,52,0b10011100,10011100,0b110100,110100,10011100110100,010011100110100
19,152,45,0b10011000,10011000,0b101101,101101,10011000101101,010011000101101
20,181,80,0b10110101,10110101,0b1010000,1010000,101101011010000,101101011010000
21,173,69,0b10101101,10101101,0b1000101,1000101,101011011000101,101011011000101
22,155,53,0b10011011,10011011,0b110101,110101,10011011110101,010011011110101
23,189,87,0b10111101,10111101,0b1010111,1010111,101111011010111,101111011010111
24,170,70,0b10101010,10101010,0b1000110,1000110,101010101000110,101010101000110
25,170,67,0b10101010,10101010,0b1000011,1000011,101010101000011,101010101000011
26,168,56,0b10101000,10101000,0b111000,111000,10101000111000,010101000111000

In [80]:
def binary_string_to_list(binary_string):
    return [int(bit) for bit in binary_string]

In [81]:
Binary_lists = [binary_string_to_list(row) for row in df2['Bin_to_qubit_15']]

In [82]:
type(Binary_lists)

list

In [83]:
Binary_lists

[[0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1],
 [0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0],
 [1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1],
 [0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0],
 [0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1],
 [1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1],
 [0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
 [1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0],
 [1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0],
 [0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0],
 [1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1],
 [1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1],
 [1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0],
 [1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0],
 [1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1],
 [1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
 [1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
 [0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0],
 [0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
 [1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0],
 [1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1],
 [0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1],
 [1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1],
 [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0],
 [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1],
 [0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0]]

In [85]:
from pennylane.templates.embeddings import BasisEmbedding

# quantum device where you want to run and how many Qubits
dev = qml.device('default.qubit', wires=15)

@qml.qnode(dev)
def circuit(data):
    for i in range(15):
        qml.Hadamard(i)
    for i in range(len(data)):
        BasisEmbedding(features=data[i], wires=range(15),do_queue=True)
    return  qml.state()

data=Binary_lists

circuit(data)

/Users/jonathanmontes/anaconda3/lib/python3.10/site-packages/pennylane/operation.py:1034: UserWarning: The do_queue keyword argument is deprecated. Instead of setting it to False, use qml.queuing.QueuingManager.stop_recording()
  warnings.warn(do_queue_deprecation_warning, UserWarning)

tensor([0.00552427+0.j, 0.00552427+0.j, 0.00552427+0.j, ...,
        0.00552427+0.j, 0.00552427+0.j, 0.00552427+0.j], requires_grad=True)

In [91]:
print(qml.draw(circuit, expansion_strategy="device")(Binary_lists))

 0: ──H──X──X──X──X──X──X──X──X──X──X──X──X──X──X──X──X──────────┤  State
 1: ──H──X──X──X──X──X──X──X──X──X──X──X─────────────────────────┤  State
 2: ──H──X──X──X──X──X──X──X──X──X──X──X──X──X──X──X─────────────┤  State
 3: ──H──X──X──X──X──X──X──X──X──X──X──X──X──X──X────────────────┤  State
 4: ──H──X──X──X──X──X──X──X──X──X──X──X──X──X───────────────────┤  State
 5: ──H──X──X──X──X──X──X──X──X──X──X──X──X──X──X──X──X──X──X────┤  State
 6: ──H──X──X──X──X──X──X──X──X──X──X──X──X──X───────────────────┤  State
 7: ──H──X──X──X──X──X──X──X──X──X──X──X──X──X───────────────────┤  State
 8: ──H──X──X──X──X──X──X──X──X──X──X──X──X──X──X──X──X──X──X──X─┤  State
 9: ──H──X──X──X──X──X──X──X──X──X──X──X─────────────────────────┤  State
10: ──H──X──X──X──X──X──X──X──X──X──X──X──X──────────────────────┤  State
11: ──H──X──X──X──X──X──X──X──X──X──X────────────────────────────┤  State
12: ──H──X──X──X──X──X──X──X──X──X──X────────────────────────────┤  State
13: ──H──X──X──X──X──X──X──X──X──X──X──X──X──────────────────────┤  State
14: ──H──X──X──X──X──X──X──X──X──X──X──X──X──X───────────────────┤  State

/Users/jonathanmontes/anaconda3/lib/python3.10/site-packages/pennylane/operation.py:1034: UserWarning: The do_queue keyword argument is deprecated. Instead of setting it to False, use qml.queuing.QueuingManager.stop_recording()
  warnings.warn(do_queue_deprecation_warning, UserWarning)